### ISSUE TITLE
data does not arrive properly in req.body (axios post method)

### ISSUE THREAD

**Issue by olafguesswhapp** [mzabriskie/axios#196]
executing a post request in a ReactJs app does generate the following req.body:
{ '{"userEmail":"user@host.com","password":"12345"}': '' }

This is my code:

return axios({
	url: 'http://localhost:3000/apitest',
	method: 'post',
	headers: {'Content-Type': 'application/x-www-form-urlencoded'},
	data: {
		userEmail: 'user@host.com',
		password: '12345'
	},
})

Thank you for any help!

**Comment by mzabriskie** [comment]
You are setting the `Content-Type` as `application/x-www-form-urlencoded`, which is not necessary. This is the default `Content-Type`. In the case that your data is JSON, as it is in your case, axios will automatically set the `Content-Type` to `application/json;charset=utf-8`, but only if the `Content-Type` hasn't been set manually. Try removing your `headers` and see if this resolves your issue.

**Comment by olafguesswhapp** [comment]
thank you for fast feedback. I tried removing the header and also tried setting the Content-Type to "application/json;charset=utf-8" -> in both cases the request does not "reach" the node/express app. And in the browser the following error messages are displayed:

"OPTIONS http://localhost:3000/apitest
xhrAdapter @ bundle.js:25307
(anonymous function) @ bundle.js:25155
dispatchRequest @ bundle.js:25151"

"XMLHttpRequest cannot load http://localhost:3000/apicheckuser. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 404."

**Comment by mzabriskie** [comment]
Sounds like you are having a problem with CORS. Are you making your requests to a different origin than where your web page is hosted? You may need to handle this on your server by responding to requests using the `OPTIONS` request method and set the `Access-Control-Allow-Origin` header. You can set it to a specific domain `Access-Control-Allow-Origin: http://example.com` or allow wild card Access-Control-Allow-Origin: *

**Comment by olafguesswhapp** [comment]
thank you - I was also looking into my CORS settings but I already had allowed wild card access:

res.header('Access-Control-Allow-Origin', '*');

**Comment by olafguesswhapp** [comment]
thanks to your feedback I implemented to OPTIONS request method correctly (found it in stack overflow):

var allowCrossDomain = function(req, res, next) {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,OPTIONS');
    res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization, Content-Length, X-Requested-With');
    // intercept OPTIONS method
    if ('OPTIONS' == req.method) {
      res.sendStatus(200);
    } else {
      next();
    }
};

app.use(allowCrossDomain);

**Comment by mzabriskie** [comment]
Glad that you got it working :)

**Comment by nikrb** [comment]
wasn't expecting my ref to this issue to appear here, apologies. _I have removed the links in my repo but seems ref is still there_
If anyone else finds this thread, upgrade to express 4 to solve the issue.

**Comment by albertchan** [comment]
I'm still seeing this issue when I do a POST, req.body is still empty. The I'm currently running Node v.6.6.0

**Comment by MatthieuHPP** [comment]
Hello,
I do have similar difficulty with POST, req.body stays undefined. I am using the 0.15.3 version of axios
On the browser side, "index.vue", the related code is : 

  axios.post('donnees/member/create', {
        Pseudo: this.pseudo,
        Email: this.email,
        Password: this.password,
        Inscription_Date: ''
      })
      .then(function (response) {
        console.log(response)
      })
      .catch(function (error) {
        console.log(error)
      })

On the server side, the route is well adressed, but req.body stays undefined

exports.member_create_post = function(req, res, next) {
  console.log('BODY ' + req.body)
}

I do not see how to go further with my bug, any idea ?

Many thanks

Matthieu

**Comment by MatthieuHPP** [comment]
It works !
I was not using the module "body-parse" :
app.use(bodyParser.json()) // handle json data
app.use(bodyParser.urlencoded({ extended: true })) // handle URL-encoded data
Matthieu

**Comment by KeepChen** [comment]
I got the same error,but when I changed my connection config `'host':'localhost'` to `'host':'127.0.0.1'` it works fine.
It is to be observed that I can connect mysql server with mysql-client command `mysql -hlocalhost -uroot -proot`.

**Comment by Lomse** [comment]
@MatthieuHPP `body-parser` not `body-parse`

**Comment by jaggu4f** [comment]
> thanks to your feedback I implemented to OPTIONS request method correctly (found it in stack overflow):
> 
> var allowCrossDomain = function(req, res, next) {
> res.header('Access-Control-Allow-Origin', '*');
> res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,OPTIONS');
> res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization, Content-Length, X-Requested-With');
> // intercept OPTIONS method
> if ('OPTIONS' == req.method) {
> res.sendStatus(200);
> } else {
> next();
> }
> };
> 
> app.use(allowCrossDomain);

Hi thank you it;s worked for me.

**Comment by ahmedyounes** [comment]
npm i --save cors
const express = require('express')
const app = express()
const cors = require('cors')

```javascript
app.use(
  cors({
    origin: "http://localhost:1234",
    credentials: true,
  })
);
app.use('/', req, res, next ....
app.listent..
```
